language: go

go:
  - 1.5
  - 1.6
  - tip

sudo: true

before_install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide

script:
  - go test $(glide novendor)
